export default [
  {
    id: 0,
    name: 'Земноморец',
    attributes: { strength: 1, perception: -1, endurance: 0, charisma: 1, intelligence: 1, agility: 1, luck: 0 },
    condition: { h: 8, m: 5, f: 5 },
    feature: '+1 защита от любого параметра брони. +2 красоты.'
  },
  {
    id: 1,
    name: 'Норд',
    attributes: { strength: 1, perception: -1, endurance: 1, charisma: 1, intelligence: 0, agility: 1, luck: 0 },
    condition: { h: 8, m: 4, f: 6 },
    feature: '50% защита от морозного урона. 2х эффект от хороших условий.',
  },
  {
    id: 2,
    name: 'Орк',
    attributes: { strength: 3, perception: -1, endurance: 3, charisma: -2, intelligence: -1, agility: 1, luck: 0 },
    condition: { h: 10, m: 2, f: 6 },
    feature: '+1 урон любым оружием.',
  },
  {
    id: 3,
    name: 'Дроу',
    attributes: { strength: -1, perception: 1, endurance: 0, charisma: -1, intelligence: 2, agility: 3, luck: -1 },
    condition: { h: 5, m: 6, f: 7 },
    feature: '50% защита от электрического урона. +2 к действиям из скрытности',
  },
  {
    id: 4,
    name: 'Эльф',
    attributes: { strength: -1, perception: 1, endurance: -2, charisma: 1, intelligence: 3, agility: 2, luck: -1 },
    condition: { h: 6, m: 7, f: 5 },
    feature: 'Накапливание попавшей вражеской магии за ход.',
  },
  {
    id: 5,
    name: 'Полурослик',
    attributes: { strength: -2, perception: -1, endurance: -1, charisma: 2, intelligence: 1, agility: 2, luck: 2 },
    condition: { h: 6, m: 5, f: 7 },
    feature: '+4 сложность при попадании по полурослику.',
  },
  {
    id: 6,
    name: 'Дварф',
    attributes: { strength: 2, perception: -1, endurance: 2, charisma: 0, intelligence: 1, agility: -2, luck: 1 },
    condition: { h: 9, m: 4, f: 5 },
    feature: '+1 урон за каждые -3 здоровья.',
  },
  {
    id: 7,
    name: 'Табакси',
    attributes: { strength: 1, perception: 2, endurance: 1, charisma: -2, intelligence: -1, agility: 2, luck: 0 },
    condition: { h: 7, m: 3, f: 8 },
    feature: 'Ночное зрение. Урон без оружия +2',
  },
  {
    id: 8,
    name: 'Тифлинг',
    attributes: { strength: 1, perception: 1, endurance: 1, charisma: 1, intelligence: 1, agility: 1, luck: -3 },
    condition: { h: 6, m: 6, f: 6 },
    feature: '50% защита от огненного урона. 2х эффект от получаемого магического баффа.',
  },
  {
    id: 9,
    name: 'Гнолл',
    attributes: { strength: 1, perception: 2, endurance: 3, charisma: -2, intelligence: -2, agility: 1, luck: 0 },
    condition: { h: 7, m: 4, f: 7 },
    feature: '+1 к атрибутам за каждые - 2 здоровья. Восстановление 1 здоровье за прием пищи.',
  },
  {
    id: 10,
    name: 'Кобольд',
    attributes: { strength: 2, perception: 0, endurance: 2, charisma: -2, intelligence: -1, agility: 1, luck: 1 },
    condition: { h: 7, m: 4, f: 7 },
    feature: 'Водное дыхание. В два раза меньше эффект от ядов против кобольда.',
  },
];